---
title: "Analysis FER & CTR: Behavioural Data"
author: "Irene Sophia Plank"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)           # kable
library(tidyverse)       # tibble stuff
library(ggplot2)         # plots
library(ggstatsplot)     # ggplot with stats

dt.path = paste('/home/emba/Documents/EMBA', 'BVET', sep = "/")
knitr::opts_knit$set(root.dir = dt.path)

```

## R Markdown

<style type="text/css">
.main-container {
  max-width: 1100px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r load_data, warning=F, message=F}
# load the relevant data in long format
df.fer = list.files(path = dt.path, pattern = "FER-BV_*", full.names = T) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "cdcdddc")) %>% 
  mutate(
    lastkey = as.numeric(lastkey)
  ) %>% 
  mutate(acc = emo == opt,
         emo = as.factor(emo),
         emo = recode_factor(emo, 
                "1" = "AF",
                "2" = "AN",
                "3" = "HA",
                "4" = "SA"),
         opt = as.factor(opt),
         opt = recode_factor(opt, 
                "1" = "AF",
                "2" = "AN",
                "3" = "HA",
                "4" = "SA"), 
         disc = case_when(
           acc ~ disc
         )) %>%
  select(subID, video, emo, disc, acc)

df.ctr = list.files(path = dt.path, pattern = "CTR-BV_*", full.names = T) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "cdcdddc")) %>% 
  mutate(
    lastkey = as.numeric(lastkey)
  ) %>% 
  mutate(acc = animal == opt,
         animal = as.factor(animal),
         animal = recode_factor(animal, 
                "1" = "ape",
                "2" = "dog",
                "3" = "cat",
                "4" = "lion"),
         opt = as.factor(opt),
         opt = recode_factor(opt, 
                "1" = "ape",
                "2" = "dog",
                "3" = "cat",
                "4" = "lion"), 
         disc = case_when(
           acc ~ disc
         )) %>%
  select(subID, video, animal, disc, acc)

# aggregate date per participant
df.fer_agg = df.fer %>% 
  group_by(subID, emo) %>%
  summarise(
    disc = mean(disc, na.rm = T),
    acc = mean(acc)
  )

df.ctr_agg = df.ctr %>% 
  group_by(subID, animal) %>%
  summarise(
    disc = mean(disc, na.rm = T),
    acc = mean(acc)
  )

# who has to be excluded? 
exc1 = df.fer %>% group_by(subID) %>% summarise(acc = mean(acc)) %>% filter(acc < 2/3)
exc2 = df.ctr %>% group_by(subID) %>% summarise(acc = mean(acc)) %>% filter(acc < 2/3)
exc = c(as.character(exc1$subID), as.character(exc2$subID))
print(length(exc)) # print how many have to be excluded

# load pilot participants and add to the list
pilot = read_csv(paste0(dt.path, "/pilot-subIDs.csv"))
exc   = c(exc, pilot$subID)

# exclude these participants
df.fer = df.fer %>% filter(!(subID %in% exc))
df.ctr = df.ctr %>% filter(!(subID %in% exc))

# save data frame
saveRDS(df.fer, "df_FER.RDS")
saveRDS(df.ctr, "df_CTR.RDS")

# how many are still left
length(unique(df.fer$subID))

```

```{r plot_data, warning = F, message = F}

ggplot(data=df.fer_agg, aes(group = emo, y = acc, colour = emo, x = emo)) +
  geom_boxplot()

ggplot(data=df.fer, aes(x = disc, fill = emo)) +
  geom_density(alpha = 0.5, colour = "darkgrey")

ggplot(data=df.ctr_agg, aes(group = animal, y = acc, colour = animal, x = animal)) +
  geom_boxplot()

ggplot(data=df.ctr, aes(x = disc, fill = animal)) +
  geom_density(alpha = 0.5, colour = "darkgrey")

```
